### PR TITLE
Add skeleton extension versions file

### PR DESCRIPTION
**Pull request by VSEphpbb**

### CODE REVIEW

**Comment by paul999** [comment]
Should there be a stable entry as it is not yet a stable version?

**Comment by VSEphpbb** [comment]
If there is no stable, will it still show up in the ACP even if they user does not have show unstable branches checked?

**Comment by paul999** [comment]
I dunno. @Nicofuma maybe?

**Comment by Nicofuma** [comment]
If an unstable extension is installed its unstable updates will be displayed.

**Comment by paul999** [comment]
In that case it should be removed from stable

**Comment by VSEphpbb** [comment]
Updated

**Pull request merged**
